INSERT ALL
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Tim Cook', 'Timcook@gmail.com', 'TCook1', '4512756891', 'CookApple', 1)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Ariana Grande','AGrande@yahoo.com','AGrande1','9376498172','Ariana Grande',1)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Elon Musk','Elonmusk@yahoo.com','EMusk1','2847201343','Elon Musk',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Chris Brown','ChrisBrown@gmail.com','ChrisBro1','4008801345','CB',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Russell Westbrook','RWestbrook@gmail.com','RWesbrook1','2318760989','Thunder Leader',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Kevin Durant','DurantKev@gmail.com','KDurant1','5345298112','KDTrey5',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Iggy Azalea','Iggy@gmail.com','Iggy1','6876498432','IGGY',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Mariah Carey','MariaCarey@gmail.com','Mcarey1','5540390182','MariahCarey',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Nicki Minaj','NickiMinaj@gmail.com','Nminaj1','4764033082','NickiMalaji',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Daniel Radcliffe','DRadcliffe@gmail.com','DRad1','2734063052','HP_Daniel',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Rihanna','Rihanna@gmail.com','Rihanna1','2723060542','Rihanna',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Justin Bieber','JBieber@gmail.com','JBieber1','8340740172','JBtheKing',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Larry Page','LarryPage@gmail.com','LarryPage1','6540320172','LarryPage',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Stephen Curry','SCurry@gmail.com','SCurry1','3412377584','WarriorChampion',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Emma Watson','EmmaWatson@yahoo.com','EWatson1','8443298162','EmWatson',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Lena Headey','Lheadey@yahoo.com','LHeadey1','1031973432','The Queen',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Kit Harington','KHarin@gmail.com','KHarin1','6340740172','Lord Commander',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Emilia Clarke','EClarke@gmail.com','EClarke1','3431193740','Khaleesi',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Peter Dinklage','PDinklage@gmail.com','PDinklage1','6753568567','The Imp',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('James Harden','JHarden@gmail.com','JHarden1','3416274384','James Harden',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Jeff Bezos','JeffBezos@yahoo.com','JBezos1','3463712649','AmazonPrime',0)
SELECT 1 FROM DUAL;