INSERT ALL
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Tim Cook', 'Timcook@gmail.com', 'TCook1', '4512756891', 'CookApple', 1)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Ariana Grande','AGrande@yahoo.com','AGrande1','9376498172','AGrande@yahoo.com',1)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Elon Musk','Elonmusk@yahoo.com','EMusk1','2847201343','Elonmusk@yahoo.com',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Chris Brown','ChrisBrown@gmail.com','ChrisBro1','4008801345','CB',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Russell Westbrook','RWestbrook@gmail.com','RWesbrook1','2318760989','Thunder Leader',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Kevin Durant','DurantKev@gmail.com','KDurant1','5345298112','KDTrey5',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Iggy Azalea','Iggy@gmail.com','Iggy1','6876498432','IGGY',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Mariah Carey','MariaCarey@gmail.com','Mcarey1','5540390182','MariahCarey',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Nicki Minaj','NickiMinaj@gmail.com','Nminaj1','4764033082','NickiMalaji',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Daniel Radcliffe','DRadcliffe@gmail.com','DRad1','2734063052','HP_Daniel',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Rihanna','Rihanna@gmail.com','Rihanna1','2723060542','Rihanna@gmail.com',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Justin Bieber','JBieber@gmail.com','JBieber1','8340740172','JBtheKing',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Larry Page','LarryPage@gmail.com','LarryPage1','6540320172','LarryPage',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Stephen Curry','SCurry@gmail.com','SCurry1','3412377584','WarriorChampion',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Emma Watson','EmmaWatson@yahoo.com','EWatson1','8443298162','EmWatson',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Lena Headey','Lheadey@yahoo.com','LHeadey1','1031973432','The Queen',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Kit Harington','KHarin@gmail.com','KHarin1','6340740172','Lord Commander',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Emilia Clarke','EClarke@gmail.com','EClarke1','3431193740','Khaleesi',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Peter Dinklage','PDinklage@gmail.com','PDinklage1','6753568567','The Imp',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('James Harden','JHarden@gmail.com','JHarden1','3416274384','James Harden',0)
	INTO UserProfile (name, email, password, phone_num, screenname, is_manager) VALUES ('Jeff Bezos','JeffBezos@yahoo.com','JBezos1','3463712649','AmazonPrime',0)

	INTO TopicWord (keyword) VALUES ('actor')
	INTO TopicWord (keyword) VALUES ('actress')
	INTO TopicWord (keyword) VALUES ('apple')
	INTO TopicWord (keyword) VALUES ('amazon')
	INTO TopicWord (keyword) VALUES ('barbadian')
	INTO TopicWord (keyword) VALUES ('basketball')
	INTO TopicWord (keyword) VALUES ('canadian')
	INTO TopicWord (keyword) VALUES ('ceo')
	INTO TopicWord (keyword) VALUES ('computer scientist')
	INTO TopicWord (keyword) VALUES ('dancer')
	INTO TopicWord (keyword) VALUES ('game of thrones')
	INTO TopicWord (keyword) VALUES ('google')
	INTO TopicWord (keyword) VALUES ('harry potter')
	INTO TopicWord (keyword) VALUES ('model')
	INTO TopicWord (keyword) VALUES ('nba')
	INTO TopicWord (keyword) VALUES ('OpenAI')
	INTO TopicWord (keyword) VALUES ('rapper')
	INTO TopicWord (keyword) VALUES ('rockets')
	INTO TopicWord (keyword) VALUES ('singer')
	INTO TopicWord (keyword) VALUES ('space x')
	INTO TopicWord (keyword) VALUES ('solarcity')
	INTO TopicWord (keyword) VALUES ('tesla')
	INTO TopicWord (keyword) VALUES ('warrior')
	INTO TopicWord (keyword) VALUES ('you_know_nothing')
	INTO TopicWord (keyword) VALUES ('veterans')
	INTO TopicWord (keyword) VALUES ('apple')
	INTO TopicWord (keyword) VALUES ('freedom')
	INTO TopicWord (keyword) VALUES ('poster')
	INTO TopicWord (keyword) VALUES ('disney')
	INTO TopicWord (keyword) VALUES ('movie')
	INTO TopicWord (keyword) VALUES ('street')
	INTO TopicWord (keyword) VALUES ('city')	
	INTO TopicWord (keyword) VALUES ('christmas')	
	INTO TopicWord (keyword) VALUES ('tv series')	
 
	INTO UserProfile_Topic (email, keyword) VALUES ('ChrisBrown@gmail.com','singer')
	INTO UserProfile_topic (email, keyword) VALUES ('ChrisBrown@gmail.com','rapper')
	INTO UserProfile_topic (email, keyword) VALUES ('ChrisBrown@gmail.com','dancer')
	INTO UserProfile_topic (email, keyword) VALUES ('RWestbrook@gmail.com','basketball')
	INTO UserProfile_topic (email, keyword) VALUES ('RWestbrook@gmail.com','thunder')
	INTO UserProfile_topic (email, keyword) VALUES ('RWestbrook@gmail.com','nba')
	INTO UserProfile_topic (email, keyword) VALUES ('DurantKev@gmail.com','basketball')
	INTO UserProfile_topic (email, keyword) VALUES ('DurantKev@gmail.com','warrior')
	INTO UserProfile_topic (email, keyword) VALUES ('DurantKev@gmail.com','nba')
	INTO UserProfile_topic (email, keyword) VALUES ('Iggy@gmail.com','singer')
	INTO UserProfile_topic (email, keyword) VALUES ('Iggy@gmail.com','rapper')
	INTO UserProfile_topic (email, keyword) VALUES ('Iggy@gmail.com','model')
	INTO UserProfile_topic (email, keyword) VALUES ('MariaCarey@gmail.com','singer')
	INTO UserProfile_topic (email, keyword) VALUES ('NickiMinaj@gmail.com','singer')
	INTO UserProfile_topic (email, keyword) VALUES ('NickiMinaj@gmail.com','rapper')
	INTO UserProfile_topic (email, keyword) VALUES ('DRadcliffe@gmail.com','actor')
	INTO UserProfile_topic (email, keyword) VALUES ('DRadcliffe@gmail.com','harry potter')
	INTO UserProfile_topic (email, keyword) VALUES ('Rihanna@gmail.com','singer')
	INTO UserProfile_topic (email, keyword) VALUES ('Rihanna@gmail.com','barbardian')
	INTO UserProfile_topic (email, keyword) VALUES ('JBieber@gmail.com','singer')
	INTO UserProfile_topic (email, keyword) VALUES ('JBieber@gmail.com','Canadian')
	INTO UserProfile_topic (email, keyword) VALUES ('LarryPage@gmail.com','google')
	INTO UserProfile_topic (email, keyword) VALUES ('LarryPage@gmail.com','ceo')
	INTO UserProfile_topic (email, keyword) VALUES ('LarryPage@gmail.com','computer scientist')
	INTO UserProfile_topic (email, keyword) VALUES ('SCurry@gmail.com','basketball')
	INTO UserProfile_topic (email, keyword) VALUES ('SCurry@gmail.com','warrior')
	INTO UserProfile_topic (email, keyword) VALUES ('SCurry@gmail.com','nba')
	INTO UserProfile_topic (email, keyword) VALUES ('EmmaWatson@yahoo.com','actress')
	INTO UserProfile_topic (email, keyword) VALUES ('Lheadey@yahoo.com','actress')
	INTO UserProfile_topic (email, keyword) VALUES ('Lheadey@yahoo.com','game of thrones')
	INTO UserProfile_topic (email, keyword) VALUES ('AGrande@yahoo.com','singer')
	INTO UserProfile_topic (email, keyword) VALUES ('AGrande@yahoo.com','actress')
	INTO UserProfile_topic (email, keyword) VALUES ('KHarin@gmail.com','actor')
	INTO UserProfile_topic (email, keyword) VALUES ('KHarin@gmail.com','game of thrones')
	INTO UserProfile_topic (email, keyword) VALUES ('KHarin@gmail.com','you_know_nothing')
	INTO UserProfile_topic (email, keyword) VALUES ('EClarke@gmail.com','actress')
	INTO UserProfile_topic (email, keyword) VALUES ('EClarke@gmail.com','game of thrones')
	INTO UserProfile_topic (email, keyword) VALUES ('PDinklage@gmail.com','actor')
	INTO UserProfile_topic (email, keyword) VALUES ('PDinklage@gmail.com','game of thrones')
	INTO UserProfile_topic (email, keyword) VALUES ('JHarden@gmail.com','basketball')
	INTO UserProfile_topic (email, keyword) VALUES ('JHarden@gmail.com','rockets')
	INTO UserProfile_topic (email, keyword) VALUES ('JHarden@gmail.com','nba')
	INTO UserProfile_topic (email, keyword) VALUES ('Timcook@gmail.com','apple')
	INTO UserProfile_topic (email, keyword) VALUES ('Timcook@gmail.com','ceo')
	INTO UserProfile_topic (email, keyword) VALUES ('Elonmusk@yahoo.com','space x')
	INTO UserProfile_topic (email, keyword) VALUES ('Elonmusk@yahoo.com','tesla')
	INTO UserProfile_topic (email, keyword) VALUES ('Elonmusk@yahoo.com','solarcity')
	INTO UserProfile_topic (email, keyword) VALUES ('Elonmusk@yahoo.com','openai')
	INTO UserProfile_topic (email, keyword) VALUES ('JeffBezos@yahoo.com','amazon')
	INTO UserProfile_topic (email, keyword) VALUES ('JeffBezos@yahoo.com','ceo')

	INTO Friendship (intitiator, receiver, is_pending) VALUES ('RWestbrook@gmail.com','DurantKev@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('RWestbrook@gmail.com','JHarden@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('RWestbrook@gmail.com','SCurry@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('DurantKev@gmail.com','JHarden@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('DurantKev@gmail.com','SCurry@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('JHarden@gmail.com','SCurry@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('KHarin@gmail.com','EClarke@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('KHarin@gmail.com','PDinklage@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('KHarin@gmail.com','Lheadey@yahoo.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('EClarke@gmail.com','PDinklage@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('EClarke@gmail.com','Lheadey@yahoo.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('PDinklage@gmail.com','Lheadey@yahoo.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('ChrisBrown@gmail.com','JBieber@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('ChrisBrown@gmail.com','Iggy@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('ChrisBrown@gmail.com','Rihanna@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('ChrisBrown@gmail.com','AGrande@yahoo.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('ChrisBrown@gmail.com','NickiMinaj@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('ChrisBrown@gmail.com','MariaCarey@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('JBieber@gmail.com','Iggy@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('JBieber@gmail.com','Rihanna@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('JBieber@gmail.com','AGrande@yahoo.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('JBieber@gmail.com','NickiMinaj@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('JBieber@gmail.com','MariaCarey@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('Iggy@gmail.com','Rihanna@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('Iggy@gmail.com','AGrande@yahoo.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('Iggy@gmail.com','NickiMinaj@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('Iggy@gmail.com','MariaCarey@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('Rihanna@gmail.com','AGrande@yahoo.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('Rihanna@gmail.com','NickiMinaj@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('Rihanna@gmail.com','MariaCarey@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('AGrande@yahoo.com','NickiMinaj@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('AGrande@yahoo.com','MariaCarey@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('NickiMinaj@gmail.com','MariaCarey@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('EmmaWatson@yahoo.com','DRadcliffe@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('Timcook@gmail.com','JeffBezos@yahoo.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('Timcook@gmail.com','Elonmusk@yahoo.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('Timcook@gmail.com','LarryPage@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('JeffBezos@yahoo.com','Elonmusk@yahoo.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('JeffBezos@yahoo.com','LarryPage@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('Elonmusk@yahoo.com','LarryPage@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('MariaCarey@gmail.com','EmmaWatson@yahoo.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('Timcook@gmail.com','SCurry@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('ChrisBrown@gmail.com','RWestbrook@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('KHarin@gmail.com','RWestbrook@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('KHarin@gmail.com','DurantKev@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('JHarden@gmail.com','Iggy@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('JHarden@gmail.com','Rihanna@gmail.com',0)
	INTO Friendship (intitiator, receiver, is_pending) VALUES ('DRadcliffe@gmail.com','JBieber@gmail.com',0)

	INTO PrivateMessage (time, sent_by, received_by, body, sender_copy_delete, receiver_copy_delete) VALUES (TIMESTAMP '2016-7-5 9:00:00','DurantKev@gmail.com','Russel Westbrook','I am going to Warriors.',0,0)	
	INTO PrivateMessage (time, sent_by, received_by, body, sender_copy_delete, receiver_copy_delete) VALUES ('7.8.2016, 10:00 PM','PDinklage@gmail.com','EClarke@gmail.com','We are gonna build ships and sail to Westeros.',0,0)
	INTO PrivateMessage (time, sent_by, received_by, body, sender_copy_delete, receiver_copy_delete) VALUES ('4.1.2016, 9:00 AM','AGrande@yahoo.com','JBieber@gmail.com',"I'm gonna stop the rumor between us",0,0)
	INTO PrivateMessage (time, sent_by, received_by, body, sender_copy_delete, receiver_copy_delete) VALUES ('4.1.2016, 9:01 AM','JBieber@gmail.com','AGrande@yahoo.com','go ahead.',0,0)

	INTO ChatGroup (gname, owner) VALUES ('Thunder Big3','DurantKev@gmail.com')	
	INTO ChatGroup (gname, owner) VALUES ('Game of Thrones','EClarke@gmail.com')
	INTO ChatGroup (gname, owner) VALUES ('CEOs','Timcook@gmail.com')

	INTO Group_Member (email, gname) VALUES ('EClarke@gmail.com','Game of Thrones')
	INTO Group_Member (email, gname) VALUES ('PDinklage@gmail.com','Game of Thrones')
	INTO Group_Member (email, gname) VALUES ('KHarin@gmail.com','Game of Thrones')
	INTO Group_Member (email, gname) VALUES ('Lheadey@yahoo.com','Game of Thrones')
	INTO Group_Member (email, gname) VALUES ('RWestbrook@gmail.com','Thunder Big3')
	INTO Group_Member (email, gname) VALUES ('DurantKev@gmail.com','Thunder Big3')
	INTO Group_Member (email, gname) VALUES ('JHarden@gmail.com','Thunder Big3')
	INTO Group_Member (email, gname) VALUES ('JeffBezos@yahoo.com','CEOs')
	INTO Group_Member (email, gname) VALUES ('Elonmusk@yahoo.com','CEOs')
	INTO Group_Member (email, gname) VALUES ('Timcook@gmail.com','CEOs')
	INTO Group_Member (email, gname) VALUES ('LarryPage@gmail.com','CEOs')

	INTO ChatGroupMessage (time, sent_by, body, gname) VALUES ('11.1.2016, 5:00 PM','DurantKev@gmail.com','We are moving forward.','Thunder Big3')
	INTO ChatGroupMessage (time, sent_by, body, gname) VALUES ('11.1.2016, 5:01 PM','James Harden','I deserve the MVP this season!','Thunder Big3')
	INTO ChatGroupMessage (time, sent_by, body, gname) VALUES ('11.1.2016, 5:02 PM','RWestbrook@gmail.com','I will lead the team to champion!','Thunder Big3')
	INTO ChatGroupMessage (time, sent_by, body, gname) VALUES ('11.1.2016, 5:03 PM','DurantKev@gmail.com','LOL. Hope to see u in western finals','Thunder Big3')
	INTO ChatGroupMessage (time, sent_by, body, gname) VALUES ('11.3.2016, 9:00 AM','EClarke@gmail.com','Do you guys see my dragons?','Game of Thrones')
	INTO ChatGroupMessage (time, sent_by, body, gname) VALUES ('11.3.2016, 9:01 AM','PDinklage@gmail.com','They almost ate me last night...','Game of Thrones')
	INTO ChatGroupMessage (time, sent_by, body, gname) VALUES ('11.3.2016, 9:02 AM','KHarin@gmail.com',"Didn't see them... fought Ramsay last night...",'Game of Thrones')
	INTO ChatGroupMessage (time, sent_by, body, gname) VALUES ('11.3.2016, 9:03 AM','Lheadey@yahoo.com',"So disappointed they didn't eat Tyrion... But it doesn't matter, I am the real queen now...",'Game of Thrones')
	INTO ChatGroupMessage (time, sent_by, body, gname) VALUES ('11.3.2016, 9:04 AM','PDinklage@gmail.com','All right...','Game of Thrones')
	INTO ChatGroupMessage (time, sent_by, body, gname) VALUES ('11.10.2016, 10:01 AM','Timcook@gmail.com','There will be no discount on Macbook Pro!','CEOs')
	INTO ChatGroupMessage (time, sent_by, body, gname) VALUES ('11.10.2016, 10:02 AM','JeffBezos@yahoo.com',"C'mon man, it's soon Black Friday...",'CEOs')
	INTO ChatGroupMessage (time, sent_by, body, gname) VALUES ('11.10.2016, 10:15 AM','Elonmusk@yahoo.com','I think surface book is better!','CEOs')
	INTO ChatGroupMessage (time, sent_by, body, gname) VALUES ('11.10.2016, 10:16 AM','JeffBezos@yahoo.com','[emoji]','CEOs') 


	INTO CustomMessage (time, sent_by, body) VALUES ('11 Nov 2016, 6:27AM','DurantKev@gmail.com','Everything about this city keeps getting better. Hitting the streets today!')
	INTO BroadcastMessage_Topic (keyword) VALUES ('street')
	INTO BroadcastMessage_Topic (keyword) VALUES ('city')
	INTO Message_Viewer (email) VALUES ('RWestbrook@gmail.com')

	INTO CustomMessage (time, sent_by, body) VALUES ('13 Nov 2016, 10:50 AM','KHarin@gmail.com','Lannisters Everywhere! Smiling Smiling Smiling')
	INTO BroadcastMessage_Topic (keyword) VALUES ('game of thrones')
	INTO BroadcastMessage_Topic (keyword) VALUES ('tv series')
	INTO Message_Viewer (email) VALUES ('Lheadey@yahoo.com')
	INTO Message_Viewer (email) VALUES ('PDinklage@gmail.com')


	INTO BroadcastMessage (time, sent_by, body, is_public) VALUES ('11 Nov 2016, 6:27AM','Timcook@gmail.com','Proud to work alongside these "&" many more veterans at Apple. We honor all the brave men "&" women who sacrificed for our freedom.',1)
	INTO BroadcastMessage_Topic (keyword) VALUES ('veterans')
	INTO BroadcastMessage_Topic (keyword) VALUES ('apple')
	INTO BroadcastMessage_Topic (keyword) VALUES ('freedom')

	INTO BroadcastMessage (time, sent_by, body, is_public) VALUES ('11 Nov 2016, 6:27AM','EmmaWatson@yahoo.com','So happy to show all of you the new teaser poster for Beauty and the Beast! I hope you like it. Love Emma x',1)
	INTO BroadcastMessage_Topic (keyword) VALUES ('poster')
	INTO BroadcastMessage_Topic (keyword) VALUES ('disney')
	INTO BroadcastMessage_Topic (keyword) VALUES ('movie')

	INTO BroadcastMessage (time, sent_by, body, is_public) VALUES ('13 Nov 2016, 10:50 AM','DurantKev@gmail.com','Lets go support our own and check out Almost Christmas!',1)
	INTO BroadcastMessage_Topic (keyword) VALUES ('city')
	INTO BroadcastMessage_Topic (keyword) VALUES ('christmas')
SELECT 1 FROM DUAL;

